'use strict';
/**
 * ============================================================================
 *  ART ARENA™ — PHASE 6 · RANDOMIZER WORD-POOL SEED
 * ============================================================================
 *  Loads server/randomizer_seed.json (the curated 10,000+ element pool,
 *  generated by ../tools/generate_randomizer.py) into `randomizer_elements`.
 *
 *  Idempotent: only runs when the table is EMPTY, and every insert uses
 *  ON CONFLICT (category, name) DO NOTHING. After a sandbox reset the DB is
 *  recreated from the foundation schema (table exists, empty) and the server
 *  re-seeds itself on startup — the JSON lives with the code, so it never
 *  has to be re-shipped.
 * ============================================================================
 */
const fs = require('fs');
const path = require('path');
const { pool, DEV } = require('./lib');

const CHUNK = 1000;

async function ensureRandomizerSeed() {
  const { rows } = await pool.query('SELECT count(*)::int AS n FROM randomizer_elements');
  if (rows[0].n > 0) {
    if (DEV) console.log(`SEED randomizer pool present (${rows[0].n} elements) — skipping`);
    return rows[0].n;
  }

  const file = path.join(__dirname, 'randomizer_seed.json');
  const data = JSON.parse(fs.readFileSync(file, 'utf8'));

  const rowsToInsert = [];
  for (const [category, entries] of Object.entries(data)) {
    for (const e of entries) {
      rowsToInsert.push({ category, name: e.name, tags: e.tags || [] });
    }
  }

  let inserted = 0;
  for (let i = 0; i < rowsToInsert.length; i += CHUNK) {
    const chunk = rowsToInsert.slice(i, i + CHUNK);
    const params = [];
    const values = chunk.map((r, j) => {
      params.push(r.category, r.name, r.tags);
      return `($${j * 3 + 1}, $${j * 3 + 2}, $${j * 3 + 3}, 'official', 'active')`;
    }).join(', ');
    const res = await pool.query(
      `INSERT INTO randomizer_elements (category, name, tags, source, status)
       VALUES ${values}
       ON CONFLICT (category, name) DO NOTHING`,
      params
    );
    inserted += res.rowCount;
  }

  console.log(`SEED randomizer pool loaded: ${inserted} elements from ${path.basename(file)}`);
  return inserted;
}

module.exports = { ensureRandomizerSeed };
